<a href="https://colab.research.google.com/github/Darshini-A/Deep-Learning/blob/main/EigenValues%20%2C%20EigenVectors%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# 2-D array

import numpy as np

m = np.array([[1, 2],
              [2, 3]])

print("Printing the Original square array:\n", m)
print()
print('***************************************')
print()

w, v = np.linalg.eig(m)

print("Printing the Eigen values of the given square array:\n", w)
print()
print("\nPrinting Right Eigen Vectors of the given square array:\n", v)

Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]


Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [12]:
# 3-D array

import numpy as np

n = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

print("Printing the Original square array:\n", n)
print()
print('***************************************')
print()

a, b = np.linalg.eig(n)

print("Printing the Eigen values of the given square array:\n", a)
print()
print("\nPrinting Right eigenvectors of the given square array:\n", b)

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]


Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [14]:
# 2-D array using tensorflow

import tensorflow as tf

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n".format(e_matrix_A))

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Matrix A: 
[[7.259452 9.190377]
 [8.488132 4.392931]]

Eigen Vectors: 
[[-0.64556265  0.7637073 ]
 [ 0.7637073   0.64556265]] 

Eigen Values: 
[-2.7820964 14.434479 ]



In [15]:
# 3-D array using tensorflow

import tensorflow as tf

e_matrix_B = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixB")
print("Matrix B: \n{}\n".format(e_matrix_B))

eigen_values_B, eigen_vectors_B = tf.linalg.eigh(e_matrix_B)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_B, eigen_values_B))

Matrix B: 
[[3.959043  7.247425  4.690694 ]
 [5.040031  4.9724793 7.219287 ]
 [8.151928  4.406246  6.9891214]]

Eigen Vectors: 
[[ 0.80077434  0.14163536  0.58197916]
 [-0.19206527 -0.8596119   0.47347456]
 [-0.567337    0.49092436  0.66115195]] 

Eigen Values: 
[-3.025327   1.6256448 17.320328 ]

