<a href="https://colab.research.google.com/github/Darshini-A/Deep-Learning/blob/main/EigenValues%20%2C%20EigenVectors%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# 2-D array

import numpy as np

m = np.array([[1, 2],
              [2, 3]])

print("Printing the Original square array:\n", m)
print()
print('********************************************************')
print()

w, v = np.linalg.eig(m)

print("Printing the Eigen values of the given square array:\n", w)
print()
print("Printing Right Eigen Vectors of the given square array:\n", v)

Printing the Original square array:
 [[1 2]
 [2 3]]

********************************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [6]:
# 3-D array

import numpy as np

n = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

print("Printing the Original square array:\n", n)
print()
print('**********************************************************')
print()

a, b = np.linalg.eig(n)

print("Printing the Eigen values of the given square array:\n", a)
print()
print("Printing Right eigenvectors of the given square array:\n", b)

Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

**********************************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [7]:
# 2-D array using tensorflow

import tensorflow as tf

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n".format(e_matrix_A))

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Matrix A: 
[[4.075759  4.8080454]
 [7.0614367 4.274633 ]]

Eigen Vectors: 
[[-0.71206754 -0.702111  ]
 [ 0.702111   -0.71206754]] 

Eigen Values: 
[-2.886941 11.237334]



In [8]:
# 3-D array using tensorflow

import tensorflow as tf

e_matrix_B = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixB")
print("Matrix B: \n{}\n".format(e_matrix_B))

eigen_values_B, eigen_vectors_B = tf.linalg.eigh(e_matrix_B)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_B, eigen_values_B))

Matrix B: 
[[6.697035  7.8760905 9.697329 ]
 [7.6398726 9.698332  6.7035217]
 [4.456567  9.690588  3.672114 ]]

Eigen Vectors: 
[[-0.14278075 -0.85364556  0.50090206]
 [ 0.6351931   0.30908638  0.7078102 ]
 [-0.75904095  0.4192312   0.49809825]] 

Eigen Values: 
[-3.599012   1.7421529 21.924337 ]

