<a href="https://colab.research.google.com/github/Darshini-A/Deep-Learning/blob/main/EigenValues%20%2C%20EigenVectors%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# computing eigenvalues & right eigenvectors using NumPy library

In [12]:
# 2-D array

import numpy as np

m = np.array([[1, 2],
              [2, 3]])

print("Printing the square array :\n", m)
print('\n********************************************************')

w, v = np.linalg.eig(m)

print("\nPrinting the Eigen Values of the square array :\n", w)
print("\nPrinting the Right Eigen Vectors of the square array :\n", v)

Printing the square array :
 [[1 2]
 [2 3]]

********************************************************

Printing the Eigen Values of the square array :
 [-0.23606798  4.23606798]

Printing the Right Eigen Vectors of the square array :
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [13]:
# 3-D array

import numpy as np

n = np.array([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

print("Printing the square array:\n", n)
print('\n********************************************************')

a, b = np.linalg.eig(n)

print("\nPrinting the Eigen Values of the square array :\n", a)
print("\nPrinting the Right Eigen Vectors of the square array :\n", b)

Printing the square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

********************************************************

Printing the Eigen Values of the square array :
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]

Printing the Right Eigen Vectors of the square array :
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [14]:
# computing eigenvalues & eigenvectors using tensorflow

In [18]:
# 2-D array using tensorflow

import tensorflow as tf

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n".format(e_matrix_A))

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors of Matrix A : \n{} \n\nEigen Values of Matrix A : \n{}\n".format(eigen_vectors_A, eigen_values_A))

Matrix A: 
[[7.474695  9.806396 ]
 [7.1052694 3.3815675]]

Eigen Vectors of Matrix A : 
[[-0.60133934  0.7989937 ]
 [ 0.7989937   0.60133934]] 

Eigen Values of Matrix A : 
[-1.9660064 12.822269 ]



In [16]:
# 3-D array using tensorflow

import tensorflow as tf

e_matrix_B = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixB")
print("Matrix B: \n{}\n".format(e_matrix_B))

eigen_values_B, eigen_vectors_B = tf.linalg.eigh(e_matrix_B)
print("Eigen Vectors of Matrix B : \n{} \n\nEigen Values of Matrix B : \n{}\n".format(eigen_vectors_B, eigen_values_B))

Matrix B: 
[[8.937064  9.608495  3.792766 ]
 [3.8467534 3.2793646 5.6868496]
 [3.1763508 3.5747545 6.685529 ]]

Eigen Vectors of Matrix B : 
[[-0.26262492 -0.6520071   0.7112767 ]
 [ 0.885711    0.12955685  0.4457924 ]
 [-0.3828107   0.7470619   0.5434651 ]] 

Eigen Values of Matrix B : 
[ 0.5937178  4.5332704 13.774967 ]

